name: location_sharing_app
description: A real-time location sharing application

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0
  google_maps_flutter: ^2.2.6
  geolocator: ^10.0.0
  geofence: ^1.0.0
  flutter_local_notifications: ^15.1.1
  provider: ^6.0.5
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/